spring.application.name=NTFurniture
server.port=8386

## JPA Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.properties.hibernate.format_sql=false
#
## Thymeleaf
#spring.thymeleaf.cache=false
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#
## ===============================
## SQL Server connection
## ===============================
#spring.datasource.url=jdbc:sqlserver://localhost:8386;databaseName=furniture;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# Google OAuth2 Login
# ===============================

#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.scope=email,profile
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=letam41225@gmail.com
spring.mail.password=yhgt qetb yhet gkhf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
